from pathlib import Path
import re


def replace_once(path, old, new):
    p=Path(path); s=p.read_text()
    if s.count(old)!=1: raise SystemExit(f'{path}: expected one exact match, got {s.count(old)}')
    p.write_text(s.replace(old,new,1))


def sub_once(path, pattern, repl, flags=0):
    p=Path(path); s=p.read_text()
    out,n=re.subn(pattern,repl,s,count=1,flags=flags)
    if n!=1: raise SystemExit(f'{path}: expected one regex match, got {n}')
    p.write_text(out)

js='js/lot2-design-3.js'
replace_once(js,"};\n\nconst COLORS=", "};\n\nconst OPENINGS=[\n  {id:'ENTRY-A',role:'entry',unit:'A',x1:80.8,y1:25,x2:81.2,y2:28,height:7},\n  {id:'GARAGE-A-CONNECTION',role:'garage-connection',unit:'A',x1:107.8,y1:15,x2:108.2,y2:18,height:7},\n  {id:'ENTRY-B',role:'entry',unit:'B',x1:76.8,y1:9,x2:77.2,y2:12,height:7},\n  {id:'GARAGE-B-CONNECTION',role:'garage-connection',unit:'B',x1:46,y1:15.8,x2:49,y2:16.2,height:7},\n  {id:'GARAGE-A-OVERHEAD',role:'garage-overhead',unit:'A',x1:128,y1:10,x2:128,y2:26,height:8},\n  {id:'GARAGE-B-OVERHEAD',role:'garage-overhead',unit:'B',x1:57,y1:18,x2:57,y2:34,height:8}\n];\n\nconst COLORS=")
replace_once(js,'aria-label="CFB-716 continuous swept path proof overlay" data-sweep-pose-count="${allPoses.length}" data-arc-pose-count="${arcCount}" data-short-tangent-count="${shortCount}" data-turn-radius-ft="${R}" data-min-clearance-ft="${minClearance.toFixed(3)}" data-outbound-proof="reverse-equivalent"','aria-label="CFB-716 continuous garage-threshold approach sweep" data-proof-scope="threshold-approach" data-full-enclosure="false" data-garage-depth-ft="20" data-depth-deficit-ft="${(VEHICLE.length-20).toFixed(1)}" data-sweep-pose-count="${allPoses.length}" data-arc-pose-count="${arcCount}" data-short-tangent-count="${shortCount}" data-turn-radius-ft="${R}" data-min-clearance-ft="${minClearance.toFixed(3)}" data-outbound-proof="threshold-return-reverse-equivalent"')
replace_once(js,'A-002 · Full-size SUV / pickup swept-path proof','A-002 · Full-size SUV / pickup garage-threshold approach sweep')
replace_once(js,'Continuous 25′ rear-axle-radius sweep derived from the frozen CFB-716 drive controls · design-development proof, not civil certification','Continuous 25′ rear-axle-radius approach sweep to the frozen garage thresholds · design-development study, not civil certification')
replace_once(js,"<text x=\"18\" y=\"24\" font-size=\"11\" font-weight=\"900\" fill=\"${ink}\">CONTINUOUS R=25′ SWEEP · MIN SOUTH-BOUNDARY CLEARANCE ${minClearance.toFixed(2)} FT</text>\n    <text x=\"18\" y=\"45\" font-size=\"10.5\" fill=\"${COLORS.muted}\">Solid line = sampled rear-axle path; dashed line = frozen drive controls. Body poses use the locked 20.5′ × 8.0′ FS-SUV and include the filleted turns.</text>\n    <text x=\"18\" y=\"64\" font-size=\"10.5\" fill=\"${COLORS.muted}\">Outbound is the reverse of the same validated path and therefore shares the same swept envelope. Pennsylvania remains the only modeled access origin.</text>","<text x=\"18\" y=\"24\" font-size=\"11\" font-weight=\"900\" fill=\"${ink}\">CONTINUOUS R=25′ APPROACH SWEEP · MIN SOUTH-BOUNDARY CLEARANCE ${minClearance.toFixed(2)} FT</text>\n    <text x=\"18\" y=\"45\" font-size=\"10.5\" fill=\"${COLORS.muted}\">Solid line = sampled rear-axle path; dashed line = frozen drive controls. Body poses use the locked 20.5′ × 8.0′ FS-SUV and include the filleted turns.</text>\n    <text x=\"18\" y=\"64\" font-size=\"10.5\" fill=\"${COLORS.muted}\">Scope: Pennsylvania ↔ garage-threshold approach only. The locked 20.5′ vehicle exceeds the nominal 20′ garage depth by 0.5′, so full enclosure / parking fit is not claimed.</text>")
replace_once(js,"function axonPts(a){return a.map(p=>p.map(v=>v.toFixed(1)).join(\",\")).join(\" \")}\n","function axonPts(a){return a.map(p=>p.map(v=>v.toFixed(1)).join(\",\")).join(\" \")}\nfunction projectAxonOpening(o){const h=o.height||7;return [[o.x1,o.y1,0],[o.x2,o.y2,0],[o.x2,o.y2,h],[o.x1,o.y1,h]].map(([x,y,z])=>axonProject(x,y,z))}\nfunction renderProjectedOpenings(mode='massing'){\n  const shown=OPENINGS.filter(o=>o.role==='entry'||o.role==='garage-overhead');\n  return `<g aria-label=\"Derived opening location overlay\">${shown.map(o=>{\n    const q=projectAxonOpening(o),fill=mode==='axon'?(o.role==='entry'?'#7f654e':'#6e6a64'):'none';\n    const top=q.slice(2),cx=(top[0][0]+top[1][0])/2,cy=(top[0][1]+top[1][1])/2-8;\n    const tag=o.role==='entry'?`<text x=\"${cx.toFixed(1)}\" y=\"${cy.toFixed(1)}\" text-anchor=\"middle\" font-size=\"9\" font-weight=\"900\" fill=\"${COLORS.navy}\">${o.id.replace('-', ' ')}</text>`:'';\n    return `<g data-opening-group=\"${o.id}\"><polygon data-opening=\"door\" data-opening-id=\"${o.id}\" data-opening-role=\"${o.role}\" data-opening-derived=\"world\" points=\"${axonPts(q)}\" fill=\"${fill}\" stroke=\"#c34232\" stroke-width=\"3\"/>${tag}</g>`;\n  }).join('')}</g>`;\n}\n")
sub_once(js,r'  <g aria-label="A-401 opening location overlay">.*?  </g>\n  <text x="1075"',"  ${renderProjectedOpenings('massing')}\n  <text x=\"1075\"",re.S)
sub_once(js,r'  <g>\n    <polygon data-opening="door" points="760,432.*?  </g>\n  <g>\n    <rect x="835"',"  ${renderProjectedOpenings('axon')}\n  <g>\n    <rect x=\"835\"",re.S)
replace_once(js,'global.Lot2Design3={REV,LOCK,VEHICLE,PLAN,COLORS,analyze,renderSite,renderSweptPath,renderFloor,renderElev,renderMassing,renderAxon,renderSections};','global.Lot2Design3={REV,LOCK,VEHICLE,OPENINGS,PLAN,COLORS,analyze,projectAxonOpening,renderSite,renderSweptPath,renderFloor,renderElev,renderMassing,renderAxon,renderSections};')

pc='js/lot2-design-3-plan-closure.js'
sub_once(pc,r"const DOORS=\[.*?\];", "const DOORS=(D.OPENINGS||[]).filter(o=>o.role==='entry'||o.role==='garage-connection').map(o=>({...o,label:o.id.replace(/-/g,' ')}));", re.S)

site='d3-site.html'
p=Path(site); s=p.read_text()
s=s.replace('PASS · physical/site and full-size SUV circulation gates cleared in Workbench.','APPROACH VERIFIED · continuous full-size SUV path to both garage thresholds. Full garage enclosure / parking fit is not claimed.')
s=s.replace('Swept-path graphics are Workbench proof overlays for design development, not civil engineering certification.','A-002 validates the on-lot approach envelope to the garage thresholds only. The locked 20.5′ vehicle is 0.5′ longer than the nominal 20′ garage depth; garage fit requires a separate design decision.')
s=s.replace('Full-size SUV swept-path proof overlay from frozen drive data. Pennsylvania-only access, garages, vehicle envelope, and recorded 1.30 ft minimum clearance are shown for customer explanation.','Full-size SUV continuous approach-sweep overlay from frozen drive data. Pennsylvania-only access, garage thresholds, vehicle envelope, and critical clearance are shown; complete garage parking fit is explicitly outside this proof.')
p.write_text(s)

qa='scripts/d3-render-qa.mjs'; p=Path(qa); s=p.read_text()
s=s.replace("if (sm.outboundProof!=='reverse-equivalent') out.push('A-002 outbound proof missing');","if (sm.proofScope!=='threshold-approach') out.push('A-002 must be scoped as threshold approach, not full garage-entry proof');\n    if (sm.fullEnclosure!==false) out.push('A-002 must explicitly state full enclosure is not proven');\n    if (Math.abs((sm.garageDepthFt||0)-20)>1e-6 || Math.abs((sm.depthDeficitFt||0)-.5)>1e-6) out.push('A-002 garage fit disclosure does not match 20.5 ft vehicle / 20 ft garage');\n    if (sm.outboundProof!=='threshold-return-reverse-equivalent') out.push('A-002 threshold-return proof missing');")
s=s.replace("if (a&&b&&(a.doors!==b.doors||a.windows!==b.windows)) out.push(`A-401/A-402 opening count mismatch ${a.doors}/${a.windows} vs ${b.doors}/${b.windows}`);","if (a&&b&&(a.doors!==b.doors||a.windows!==b.windows)) out.push(`A-401/A-402 opening count mismatch ${a.doors}/${a.windows} vs ${b.doors}/${b.windows}`);\n    const truth=m.axonOpeningTruth;\n    if (!truth || !truth.ok) out.push('A-401/A-402 door overlays are not derived from shared world opening geometry: '+JSON.stringify(truth||{}));")
s=s.replace("const sweepMeta=sweepEl?{poseCount:Number(sweepEl.getAttribute('data-sweep-pose-count')),arcPoseCount:Number(sweepEl.getAttribute('data-arc-pose-count')),shortTangentCount:Number(sweepEl.getAttribute('data-short-tangent-count')),turnRadiusFt:Number(sweepEl.getAttribute('data-turn-radius-ft')),minClearanceFt:Number(sweepEl.getAttribute('data-min-clearance-ft')),outboundProof:sweepEl.getAttribute('data-outbound-proof')||''}:null;","const sweepMeta=sweepEl?{proofScope:sweepEl.getAttribute('data-proof-scope')||'',fullEnclosure:sweepEl.getAttribute('data-full-enclosure')==='true',garageDepthFt:Number(sweepEl.getAttribute('data-garage-depth-ft')),depthDeficitFt:Number(sweepEl.getAttribute('data-depth-deficit-ft')),poseCount:Number(sweepEl.getAttribute('data-sweep-pose-count')),arcPoseCount:Number(sweepEl.getAttribute('data-arc-pose-count')),shortTangentCount:Number(sweepEl.getAttribute('data-short-tangent-count')),turnRadiusFt:Number(sweepEl.getAttribute('data-turn-radius-ft')),minClearanceFt:Number(sweepEl.getAttribute('data-min-clearance-ft')),outboundProof:sweepEl.getAttribute('data-outbound-proof')||''}:null;\n    const axonOpeningTruth=window.Lot2Design3&&window.Lot2Design3.OPENINGS&&window.Lot2Design3.projectAxonOpening?(()=>{\n      const expected=window.Lot2Design3.OPENINGS.filter(o=>o.role==='entry'||o.role==='garage-overhead');\n      const checks={};\n      for(const id of ['massing-drawing','axon-drawing']){\n        const root=document.getElementById(id); if(!root){checks[id]={ok:false,reason:'missing figure'};continue}\n        const actual=[...root.querySelectorAll('[data-opening=\"door\"]')];\n        let ok=actual.length===expected.length; const details=[];\n        for(const o of expected){\n          const el=actual.find(x=>x.getAttribute('data-opening-id')===o.id); if(!el){ok=false;details.push(o.id+':missing');continue}\n          if(el.getAttribute('data-opening-derived')!=='world'){ok=false;details.push(o.id+':not-derived')}\n          const got=(el.getAttribute('points')||'').trim().split(/\\s+/).map(pair=>pair.split(',').map(Number));\n          const want=window.Lot2Design3.projectAxonOpening(o);\n          const delta=Math.max(...want.map((p,i)=>Math.hypot(p[0]-(got[i]?.[0]??9999),p[1]-(got[i]?.[1]??9999))));\n          if(delta>.2){ok=false;details.push(o.id+':projection-delta='+delta.toFixed(2))}\n        }\n        checks[id]={ok,details,count:actual.length};\n      }\n      return {ok:Object.values(checks).every(x=>x.ok),checks};\n    })():null;")
s=s.replace("sweepMeta,\n    };","sweepMeta,\n      axonOpeningTruth,\n    };")
p.write_text(s)

exp='js/lot2-export.js'; p=Path(exp); s=p.read_text().replace('Walk site and swept path, plans and bubble, elevations, massing and axon, then sections.','Walk site and garage-threshold approach sweep, plans and bubble, elevations, massing and axon, then sections.')
p.write_text(s)

print('final blockers patch applied')
