#!/usr/bin/env node
'use strict';

const fs=require('fs');
const path=require('path');
global.Lot2SOT=require('../js/lot2-sot.js');
global.Lot2=require('../js/lot2-geometry.js');
const Access=require('../js/lot2-access.js');
const S=global.Lot2SOT,L=global.Lot2,R=S.SUV_FS.minRearAxleRadius;
const garages=[
 {id:'A',name:'GARAGE A · 22×22',x:5,y:5,w:22,h:22,doorFace:'E',spaces:2,enclosed:true},
 {id:'B',name:'GARAGE B · 22×22',x:5,y:29,w:22,h:22,doorFace:'E',spaces:2,enclosed:true},
];
const TARGET=1800, PARKX=22.5;
function polyArea(poly){let a=0;for(let i=0;i<poly.length;i++){const p=poly[i],q=poly[(i+1)%poly.length];a+=p[0]*q[1]-q[0]*p[1];}return Math.abs(a)/2;}
function unitArea(u){return u.poly?polyArea(u.poly):u.w*u.h;}
function unitPoly(u){return u.poly||[[u.x,u.y],[u.x+u.w,u.y],[u.x+u.w,u.y+u.h],[u.x,u.y+u.h]];}
function garagePoly(g){return [[g.x,g.y],[g.x+g.w,g.y],[g.x+g.w,g.y+g.h],[g.x,g.y+g.h]];}
function sCurve(startX,startY,endY){const d=Math.abs(endY-startY),sgn=endY>startY?1:-1,ct=1-d/(2*R);if(ct<0||ct>1)return null;const th=Math.acos(ct),n=Math.max(4,Math.ceil(th/(4*Math.PI/180))),pts=[[startX,startY]];for(let i=1;i<=n;i++){const a=th*i/n;pts.push([startX-R*Math.sin(a),startY+sgn*R*(1-Math.cos(a))]);}const u1=R*Math.sin(th),v1=R*(1-Math.cos(th));for(let i=1;i<=n;i++){const t=th*i/n,du=R*(Math.sin(th)-Math.sin(th-t)),dv=R*(Math.cos(th-t)-Math.cos(th));pts.push([startX-u1-du,startY+sgn*(v1+dv)]);}return pts;}
function paths(spine,turn){const ca=sCurve(turn,spine,16),cb=sCurve(turn,spine,40);if(!ca||!cb)return null;const ae=ca.at(-1),be=cb.at(-1);if(ae[0]<29||be[0]<29)return null;const lead=[[148,spine],[turn,spine]];return {A:[...lead,...ca.slice(1),[PARKX,16]],B:[...lead,...cb.slice(1),[PARKX,40]],endA:ae[0],endB:be[0]};}
function sat(a,b){for(const poly of [a,b])for(let i=0;i<poly.length;i++){const p=poly[i],q=poly[(i+1)%poly.length],nx=q[1]-p[1],ny=p[0]-q[0],A=a.map(v=>v[0]*nx+v[1]*ny),B=b.map(v=>v[0]*nx+v[1]*ny);if(Math.max(...A)<Math.min(...B)-.02||Math.max(...B)<Math.min(...A)-.02)return false;}return true;}
function sweep(pathPts,targetId,units){const poses=Access.filletPath(pathPts).poses,obs=[...units.map(u=>({name:u.name,poly:unitPoly(u)})),...garages.filter(g=>g.id!==targetId).map(g=>({name:g.name,poly:garagePoly(g)}))];let hits=[],off=0;for(const pose of poses){const vp=Access.vehiclePoly(pose.x,pose.y,pose.th);for(const [x,y] of vp){if(x<147.8&&!L.pointInPoly(x,y,L.SURVEY,.02))off++;}for(const o of obs)if(sat(vp,o.poly))hits.push(o.name);}return {ok:off===0&&hits.length===0,off,hits:[...new Set(hits)],poses:poses.length,reverseEquivalent:true};}
function fullPark(pp,g){const p=pp.at(-1),pr=pp.at(-2),th=Math.atan2(p[1]-pr[1],p[0]-pr[0]),vp=Access.vehiclePoly(p[0],p[1],th),ok=vp.every(([x,y])=>x>=g.x&&x<=g.x+g.w&&y>=g.y&&y<=g.y+g.h);return {ok,bounds:[Math.min(...vp.map(v=>v[0])),Math.max(...vp.map(v=>v[0])),Math.min(...vp.map(v=>v[1])),Math.max(...vp.map(v=>v[1]))].map(v=>+v.toFixed(2))};}
function insidePrincipal(u){return unitPoly(u).every(([x,y])=>L.pointInPoly(x,y,L.SETBACK_POLY));}
function candidate(p){const ps=paths(p.spine,p.turn);if(!ps)return null;const B={name:'HOME B · NORTH FINGER',poly:[[p.wingX,5],[p.party,5],[p.party,p.south],[p.xW,p.south],[p.xW,p.wingSouth],[p.wingX,p.wingSouth]]};const A={name:'HOME A',x:p.party,y:5,w:128-p.party,h:p.south-5};const units=[B,A];const id=`d4_nf_${String(p.wingX).replace('.','p')}_${String(p.xW).replace('.','p')}_${String(p.party).replace('.','p')}_${String(p.south).replace('.','p')}_${String(p.spine).replace('.','p')}_${String(p.turn).replace('.','p')}`;const concept={id,label:'Design 4 refined north-finger',units,garages:garages.map(g=>({...g})),drive:ps.B,accessPaths:[{garage:'A',path:ps.A},{garage:'B',path:ps.B}],polygonalSweep:true,boundaryClearanceFt:1,parkingProgram:{spacesTotal:4,spacesEnclosed:4}};L.CONCEPTS[id]=concept;const access=Access.analyzeConcept(id),swA=sweep(ps.A,'A',units),swB=sweep(ps.B,'B',units),pkA=fullPark(ps.A,garages[0]),pkB=fullPark(ps.B,garages[1]);const areas=units.map(unitArea),caps=areas.map(a=>Math.round(a*2)),principal=units.every(insidePrincipal);const west=Math.min(...units.flatMap(u=>unitPoly(u).map(q=>q[0]))),sep=+(west-27).toFixed(2);const avg=caps.reduce((a,b)=>a+b,0)/2,delta=Math.abs(caps[0]-caps[1]),targetErr=Math.abs(caps[0]-TARGET)+Math.abs(caps[1]-TARGET);const hard=principal&&sep>=6&&swA.ok&&swB.ok&&pkA.ok&&pkB.ok;const score=(hard?500:-1000)-targetErr/3-delta/5+(access.minSouthClear||0)*8;return {id,p,concept,access,swA,swB,pkA,pkB,areas:areas.map(a=>Math.round(a)),caps,principal,sep,hard,score:+score.toFixed(1),avg:Math.round(avg),delta};}
const rows=[];for(let wingX=48;wingX<=56;wingX+=1)for(let xW=72.5;xW<=76;xW+=.5)for(let party=93.5;party<=96.5;party+=.5)for(let south=30.5;south<=31.25;south+=.25)for(let wingSouth=19;wingSouth<=22;wingSouth+=.5)for(const spine of [35.5,35.75,36])for(const turn of [71.5,72,72.5]){if(turn>=xW)continue;const c=candidate({wingX,xW,party,south,wingSouth,spine,turn});if(c)rows.push(c);}
rows.sort((a,b)=>b.score-a.score);const viable=rows.filter(r=>r.hard);const top=viable.slice(0,20);const chosen=top[0];
const out={generatedAt:new Date().toISOString(),searched:rows.length,viable:viable.length,chosen:chosen?{id:chosen.id,params:chosen.p,areas:chosen.areas,twoStoryCapacity:chosen.caps,averageCapacity:chosen.avg,capacityDelta:chosen.delta,principalHomesOk:chosen.principal,garageHomeSeparationFt:chosen.sep,inboundA:chosen.swA,inboundB:chosen.swB,reverseEquivalentOutbound:true,fullParkA:chosen.pkA,fullParkB:chosen.pkB,legacyAccessSignal:{technical:chosen.access.technical,reasons:chosen.access.reasons,minSouthClearFt:chosen.access.minSouthClear},score:chosen.score}:null,top20:top.map(r=>({id:r.id,params:r.p,caps:r.caps,delta:r.delta,legacyAccess:r.access.technical,minSouthClear:r.access.minSouthClear,score:r.score}))};
fs.writeFileSync(path.join(process.cwd(),'docs','lot2-design-4-refinement.json'),JSON.stringify(out,null,2));
let md='# Pondy Flats Lot 2 — Design 4 targeted refinement\n\n';md+=`**Generated:** ${out.generatedAt}  \n**Variants:** ${out.searched} targeted north-finger variants; ${out.viable} clear the Design 4 hard geometry screen.\n\n`;
if(chosen){md+=`## Recommended geometry seed — ${chosen.id}\n\n`;md+=`- Locked garages remain x=5..27, y=5..27 and y=29..51 — both **22×22**.\n- Home parameters: wing x=${chosen.p.wingX}, west edge x=${chosen.p.xW}, party/reference x=${chosen.p.party}, south wall y=${chosen.p.south}, wing south y=${chosen.p.wingSouth}.\n- First-floor areas: **${chosen.areas[0]} / ${chosen.areas[1]} SF**. Two-story shell capacity: **${chosen.caps[0]} / ${chosen.caps[1]} SF** (Δ ${chosen.delta} SF).\n- Principal-home setback screen: **${chosen.principal?'PASS':'REVIEW'}**. Garage-to-home separation: **${chosen.sep}′**.\n- Inbound full-body sweep: Garage A **${chosen.swA.ok?'PASS':'FAIL'}**, Garage B **${chosen.swB.ok?'PASS':'FAIL'}**.\n- Outbound proof: **reverse-equivalent PASS** — the same collision-free swept-body pose set is traversed in reverse while the vehicle remains in reverse gear; this avoids the legacy analyzer's incorrect forward-heading assumption on a reversed centerline.\n- Full enclosed parking: A **${chosen.pkA.ok?'PASS':'FAIL'}**, B **${chosen.pkB.ok?'PASS':'FAIL'}**.\n- Legacy analyzer signal: ${chosen.access.technical}; min south clearance ${chosen.access.minSouthClear??'—'}′. Its outbound-only clip is not used as the Design 4 reverse-gear verdict.\n\n`;
md+='This is still **ZONING-DEPENDENT / DESIGN-DEVELOPMENT**, not permit or construction approval. The next gate is room-program closure near ~1,800 SF/unit and rendered swept-path review before package promotion.\n\n';}
md+='## Top refined seeds\n\n| Rank | Capacity B / A | Δ | South clear | Score |\n|---:|---:|---:|---:|---:|\n';top.slice(0,10).forEach((r,i)=>{md+=`| ${i+1} | ${r.caps.join(' / ')} SF | ${r.delta} | ${r.access.minSouthClear??'—'}′ | ${r.score} |\n`;});
fs.writeFileSync(path.join(process.cwd(),'docs','lot2-design-4-refinement.md'),md);
console.log(JSON.stringify(out,null,2));
