'use strict';
// Exact-head final-QA trigger. Export output remains deterministic.
const fs=require('fs');const path=require('path');
const root=path.resolve(__dirname,'..');
const client=path.join(root,'packages','design-4-client');
const presenter=path.join(root,'packages','design-4-presenter');
function reset(dir){fs.rmSync(dir,{recursive:true,force:true});fs.mkdirSync(dir,{recursive:true});}
function copy(src,dst){fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(path.join(root,src),dst);}
function write(dst,txt){fs.mkdirSync(path.dirname(dst),{recursive:true});fs.writeFileSync(dst,txt);}
function clientNav(){return '<nav class="nav" aria-label="Primary"><a href="index.html">Design 4</a><a href="site.html">Site</a><a href="plans.html">Plans</a><a href="elevs.html">Elevs</a><a href="axon.html">Axon</a><a href="sections.html">Sections</a></nav>';}
function transform(html){
  html=html.replace(/<nav class="nav" aria-label="Primary">[\s\S]*?<\/nav>/,clientNav());
  const map={'design-4.html':'index.html','d4-site.html':'site.html','d4-plans.html':'plans.html','d4-elevs.html':'elevs.html','d4-axon.html':'axon.html','d4-sections.html':'sections.html'};
  for(const [a,b] of Object.entries(map))html=html.split(a).join(b);
  html=html.replace(/<a[^>]+href="https:\/\/lotscope\.aerovista\.us[^>]*>[\s\S]*?<\/a>/gi,'');
  return html;
}
reset(client);reset(presenter);
for(const f of ['css/lot2-client.css','js/lot2-design-4.js','js/lot2-design-4-plan-closure.js','js/lot2-design-4-architecture.js'])copy(f,path.join(client,f));
const pages={'design-4.html':'index.html','d4-site.html':'site.html','d4-plans.html':'plans.html','d4-elevs.html':'elevs.html','d4-axon.html':'axon.html','d4-sections.html':'sections.html'};
for(const [src,dst] of Object.entries(pages))write(path.join(client,dst),transform(fs.readFileSync(path.join(root,src),'utf8')));
write(path.join(client,'README.md'),`# Pondy Flats Lot 2 — Design 4 client package\n\nStandalone design-development concept package.\n\n- Two detached 22×22 garages.\n- Pennsylvania-only modeled vehicle access.\n- Full-size vehicle enclosed parking fit + reverse-equivalent back-out.\n- Two 3-bedroom diagrammed home programs.\n- Accessory zoning and inter-garage spacing remain conditional/AHJ items.\n- Not permit or construction documents.\n`);
const pStyle=`<style>body{font-family:Inter,system-ui,sans-serif;background:#f4f1eb;color:#18212b;margin:0}.wrap{max-width:980px;margin:auto;padding:36px 22px}.card{background:#fff;border-radius:18px;padding:24px;margin:16px 0;box-shadow:0 12px 34px #0d1b3312}h1,h2{font-family:Georgia,serif;color:#0d1b33}.tag{font-weight:900;color:#9a6723;font-size:12px;letter-spacing:.08em;text-transform:uppercase}.warn{border-left:4px solid #a9612b}.ok{border-left:4px solid #507759}li{margin:8px 0;line-height:1.45}a{color:#0d1b33;font-weight:800}</style>`;
write(path.join(presenter,'index.html'),`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Design 4 Presenter</title>${pStyle}</head><body><main class="wrap"><section class="card"><div class="tag">Pondy Flats · Lot 2</div><h1>Design 4 presenter kit</h1><p>North-finger homes + two full 22×22 detached rear garages.</p></section><section class="card ok"><h2>Lead with the solved problem</h2><ul><li>Two real 22×22 detached garages remain intact.</li><li>The 20.5×8.0 full-size vehicle fits completely inside each garage.</li><li>Inbound geometry and reverse-equivalent backing out are demonstrated.</li><li>Both homes carry three-bedroom diagrammed programs at about 1,784 / 1,759 SF gross shell area.</li></ul></section><section class="card warn"><h2>Say the open items plainly</h2><ul><li>Accessory zoning remains parcel-specific confirmation work.</li><li>About 2 ft between the two rear garages remains building/fire/eave/drainage/AHJ review.</li><li>Forward turnaround inside the garage is not claimed.</li><li>Structure, code, MEP, civil, survey/easements, drainage, energy and permit validation remain professional work.</li></ul></section><section class="card"><h2>Recommended walkthrough</h2><ol><li>Overview / why Design 4 exists.</li><li>A-001 site and ownership.</li><li>A-002 full-size vehicle proof.</li><li>A-101–103 plans and 3-bedroom program.</li><li>A-201–204 architectural read.</li><li>A-401/402 same-camera massing and axon.</li><li>A-301/302 sections and professional-validation boundary.</li></ol><p><a href="talking-points.html">Open detailed talking points →</a></p></section></main></body></html>`);
write(path.join(presenter,'talking-points.html'),`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Design 4 Talking Points</title>${pStyle}</head><body><main class="wrap"><section class="card"><h1>Design 4 talking points</h1><p><strong>Positioning:</strong> This is the rear-garage option that protects full 22×22 garage utility first, then solves the two homes around that constraint.</p><h2>Customer-readable facts</h2><ul><li>Garage B is north and belongs to Home B. Garage A is south and belongs to Home A.</li><li>Pennsylvania is the only modeled vehicle access.</li><li>Both garages are detached accessory structures with no living space.</li><li>Home B: about 1,784 SF gross diagram shell; Home A: about 1,759 SF.</li><li>Each diagrammed plan has three bedrooms.</li></ul><h2>Do not overclaim</h2><p>Do not call the concept zoning-approved, code-approved, permit-ready, structurally validated, civil-certified, or construction-ready. The ~2 ft garage-to-garage condition is unresolved until professional/AHJ confirmation.</p></section></main></body></html>`);
write(path.join(presenter,'README.md'),'# Design 4 presenter kit\n\nInternal presentation aid for the Design 4 design-development concept. Keep all professional/AHJ caveats intact.\n');
console.log(JSON.stringify({client,presenter,pages:Object.values(pages)},null,2));