'use strict';
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const client=path.join(root,'packages','design-4-client');
const presenter=path.join(root,'packages','design-4-presenter');
function reset(dir){fs.rmSync(dir,{recursive:true,force:true});fs.mkdirSync(dir,{recursive:true});}
function copy(src,dst){fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(path.join(root,src),dst);}
function write(dst,txt){fs.mkdirSync(path.dirname(dst),{recursive:true});fs.writeFileSync(dst,txt);}
function clientNav(){return '<nav class="nav" aria-label="Primary"><a href="index.html">Design 4</a><a href="site.html">Site</a><a href="plans.html">Plans</a><a href="elevs.html">Elevs</a><a href="axon.html">Axon</a><a href="sections.html">Sections</a></nav>';}
function transform(html){html=html.replace(/<nav class="nav" aria-label="Primary">[\s\S]*?<\/nav>/,clientNav());const map={'design-4.html':'index.html','d4-site.html':'site.html','d4-plans.html':'plans.html','d4-elevs.html':'elevs.html','d4-axon.html':'axon.html','d4-sections.html':'sections.html'};for(const [a,b] of Object.entries(map))html=html.split(a).join(b);return html.replace(/<a[^>]+href="https:\/\/lotscope\.aerovista\.us[^>]*>[\s\S]*?<\/a>/gi,'');}
reset(client);reset(presenter);
for(const f of ['css/lot2-client.css','js/lot2-workbench-audit.js','js/lot2-design-4.js','js/lot2-design-4-plan-closure.js','js/lot2-design-4-architecture.js'])copy(f,path.join(client,f));
const pages={'design-4.html':'index.html','d4-site.html':'site.html','d4-plans.html':'plans.html','d4-elevs.html':'elevs.html','d4-axon.html':'axon.html','d4-sections.html':'sections.html'};
for(const [src,dst] of Object.entries(pages))write(path.join(client,dst),transform(fs.readFileSync(path.join(root,src),'utf8')));
write(path.join(client,'README.md'),`# Pondy Flats Lot 2 — Design 4 client package\n\nStandalone design-development concept package.\n\n- Two detached 22×22 garages remain locked.\n- Four simultaneous full-size enclosed parking positions are modeled.\n- Pennsylvania-only modeled vehicle access.\n- A real-width 10 ft concept drive lane and 25 ft local maneuver apron are shown.\n- Individual stall access is governed by the Workbench full-body path audit; do not substitute the retired centered-path claim.\n- Two three-bedroom diagrammed home programs include explicit room/stair connectivity gates.\n- Accessory zoning and the roughly 2 ft inter-garage condition remain conditional/AHJ items.\n- Not permit, civil, code, structural, or construction documents.\n`);
const style='<style>body{font-family:Inter,system-ui,sans-serif;background:#f4f1eb;color:#18212b;margin:0}.wrap{max-width:980px;margin:auto;padding:36px 22px}.card{background:#fff;border-radius:18px;padding:24px;margin:16px 0;box-shadow:0 12px 34px #0d1b3312}h1,h2{font-family:Georgia,serif;color:#0d1b33}.tag{font-weight:900;color:#9a6723;font-size:12px;letter-spacing:.08em;text-transform:uppercase}.warn{border-left:4px solid #a9612b}.ok{border-left:4px solid #507759}li{margin:8px 0;line-height:1.45}a{color:#0d1b33;font-weight:800}</style>';
write(path.join(presenter,'index.html'),`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Design 4 Presenter</title>${style}</head><body><main class="wrap"><section class="card"><div class="tag">Pondy Flats · Lot 2</div><h1>Design 4 presenter kit</h1><p>North-finger homes + two full 22×22 detached rear garages + four locked enclosed stalls.</p></section><section class="card ok"><h2>What the current model establishes</h2><ul><li>Both 22×22 garage plates remain intact.</li><li>Four 20.5×8.0 full-size vehicle bodies fit simultaneously inside the garages.</li><li>A 10 ft concept access lane and widened 25 ft local maneuver apron are modeled at real width.</li><li>Both homes carry three-bedroom planning diagrams with explicit stair/room connectivity gates.</li><li>Elevations derive from real shell edges and use the red-door / blue-window opening audit contract.</li></ul></section><section class="card warn"><h2>Say the open items plainly</h2><ul><li>Individual vehicle routes are governed by the autonomous Workbench full-body audit; use only the latest passing audit evidence.</li><li>The previous ~1.08 ft centered-path claim is retired.</li><li>Accessory zoning remains parcel-specific confirmation work.</li><li>About 2 ft between rear garages remains building/fire/eave/drainage/AHJ review.</li><li>Structure, code, MEP, civil, survey/easements, drainage, energy and permit validation remain professional work.</li></ul></section><section class="card"><h2>Recommended walkthrough</h2><ol><li>Overview / locked four-stall goal.</li><li>A-001 site, real-width pavement and ownership.</li><li>A-002 Workbench vehicle audit boundary.</li><li>A-101–103 connected three-bedroom planning diagrams.</li><li>A-201–204 polygon-derived elevations.</li><li>A-401/402 same-camera massing and axon.</li><li>A-301/302 sections and professional-validation boundary.</li></ol></section></main></body></html>`);
write(path.join(presenter,'talking-points.html'),`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Design 4 Talking Points</title>${style}</head><body><main class="wrap"><section class="card"><h1>Design 4 talking points</h1><p><strong>Positioning:</strong> protect four practical enclosed stalls in two full 22×22 detached garages, then solve the homes and access around them.</p><h2>Customer-readable facts</h2><ul><li>Garage B is north and belongs to Home B; Garage A is south and belongs to Home A.</li><li>Pennsylvania is the only modeled vehicle access.</li><li>Both garages are detached accessory structures with no living space.</li><li>Home B is about 1,784 SF gross diagram shell; Home A about 1,759 SF.</li><li>Each planning diagram has three bedrooms and a connectivity-gated circulation path.</li></ul><h2>Do not overclaim</h2><p>Do not call the concept zoning-approved, code-approved, permit-ready, structurally validated, civil-certified, or construction-ready. Use Workbench audit results as design-development geometry evidence only.</p></section></main></body></html>`);
write(path.join(presenter,'README.md'),'# Design 4 presenter kit\n\nInternal presentation aid for the Design 4 design-development concept. Keep all Workbench and professional/AHJ caveats intact.\n');
console.log(JSON.stringify({client,presenter,pages:Object.values(pages)},null,2));
